name: Java Maven Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use 'temurin' for Eclipse Temurin (Adoptium)
          java-version: '17'
          cache: 'maven'  # Caches Maven dependencies for faster builds

      - name: Verify Java & Maven installation
        run: |
          java -version
          mvn -version

      - name: Build with Maven
        run: mvn clean install

