name: Check JDK Version

on:
  push:
  pull_request:

jobs:
  check-jdk-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Default JDK Version
        run: java -version

      - name: Check javac Version
        run: javac -version

      - name: Verify JAVA_HOME
        run: echo $JAVA_HOME
